version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=localDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d10medes
      - PGDATA=/var/lib/postgresql/data/data
      - POSTGRES_HOST_AUTH_METHOD=trust
    build: ./backend
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data/data
    ports:
      - "5431:5431"
    container_name: db
    expose:
      - 5431
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    links:
      - backend:backend
    expose:
      - 5000
