version: "3.8"

services:  
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  frontend:
    build: 
      context: ./frontend
    ports:
      - "14014:80"
    depends_on:
      - backend
    links:
      - backend:backend
volumes:
  postgres_data: