# Generated by Django 4.0.3 on 2022-03-27 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dollars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amountInPesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amountInDollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amountInLocal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('localCurrency', models.CharField(blank=True, max_length=20, null=True)),
                ('localCurrencyCode', models.CharField(blank=True, max_length=20, null=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dollars.movement')),
            ],
        ),
    ]
