# Generated by Django 4.0.3 on 2022-04-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollars', '0002_movementdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='sellValue',
            field=models.CharField(blank=True, choices=[('1', 'Bank'), ('2', 'AIRTM')], default='1', max_length=4, null=True),
        ),
    ]
