# Generated by Django 4.0.3 on 2022-03-20 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_payment_estimated_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher',
            field=models.FileField(blank=True, default='', null=True, upload_to='vouchers/'),
        ),
    ]
